name = "SimpleTensorNetworks"
uuid = "4456351a-5be3-4067-ade9-541926a41e04"
authors = ["GiggleLiu <cacate0129@gmail.com> and contributors"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[targets]
test = ["Test", "OMEinsum"]
